[build]
builder = "NIXPACKS"
buildCommand = "cd website && npm ci && npm run build"

[deploy]
startCommand = "cd website && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
